Repository fosslight/fosslight, pull requests merged in 2021-08, with the labels that each got.

#23 Run PR action for all branches
  .github/workflows/pull-request.yml
Labels: chore

#17 Fix a bug to create directories
  src/main/java/oss/fosslight/util/FileUtil.java
Labels: bug fix

#22 Fix a bug related to load properties
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/resources/application.properties
Labels: bug fix

#25 Remove warning message
  src/main/java/oss/fosslight/scheduler/SchedulerWorkerTask.java
  src/main/java/oss/fosslight/service/NvdDataService.java
Labels: bug fix, good first issue

#27 Bug fix - validation check
  .github/workflows/pull-request.yml
  db/conf.d/db_config.cnf
  db/initdb.d/fosslight_create.sql
  docker-compose.yml
  src/main/java/oss/fosslight/CoTopComponent.java
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/scheduler/SchedulerWorkerTask.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/StatisticsServiceImpl.java
  src/main/java/oss/fosslight/util/FileUtil.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/main/resources/messages/message.properties
  src/main/resources/messages/validation.properties
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
  src/main/resources/template/email/ossInfo.html
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/distribution-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/list.jsp
Labels: bug fix, enhancement

#31 Update .gitignore to ignore personal data folders
  .gitignore
Labels: chore

#32 Fix Typo
  src/main/java/oss/fosslight/controller/ExcelDownloadController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
Labels: chore

#34 Fix typo in CoTopComponent.java in fosslight
  src/main/java/oss/fosslight/CoTopComponent.java
Labels: chore

#38 Fix gradew file permission
  gradlew
Labels: chore

#41 Typo in Class
  src/main/java/oss/fosslight/controller/DownloadProcController.java
Labels: chore

#45 Add DROP status to project search
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
Labels: bug fix

#46 Fix Timezone to Asia/Seoul
  docker-compose.yml
Labels: chore

#48 FIx typo 'website' in UI
  src/main/webapp/WEB-INF/views/admin/license/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/license/list.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/viewpopup.jsp
Labels: chore

#50 Add to show docker-compose log in github-actions
  .github/workflows/pull-request.yml
Labels: Improvement

#55 Move the Drop button to the right of the Delete button in "Project > Basic Information"
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
Labels: chore

#56 Update the function related to detected license and changing status
  .github/workflows/pull-request.yml
  .gitignore
  docker-compose.yml
  gradlew
  src/main/java/oss/fosslight/CoTopComponent.java
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/controller/DownloadProcController.java
  src/main/java/oss/fosslight/controller/ExcelDownloadController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/logback-spring.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/template/email/ossInfo.html
  src/main/webapp/WEB-INF/views/admin/license/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/license/list.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/viewpopup.jsp
Labels: bug fix, chore, Improvement

#58 Add auto-updating CHANGELOG.md on develop branch
  .github/workflows/release-publish.yml
Labels: chore

#68 Deploy the latest release to demo.fosslight.org
  .github/workflows/release-publish.yml
Labels: chore

#61 Fix a bug for type check error.
  src/main/webapp/WEB-INF/views/admin/license/view-js.jsp
Labels: bug fix

#65 Update message.properties
  src/main/resources/messages/message.properties
Labels: documentation

#62 Add License Type option for OSS List search
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
Labels: enhancement

#63 Change Admin can Restart/Complete with no comment
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Labels: chore

#66 Add CVE link to vulnerability discovered mail body (#64)
  src/main/resources/template/email/vulnerabilityInfo.html
Labels: enhancement

#73 Fix toggle button color to match others
  src/main/resources/static/images/bg_toggle.png
Labels: chore

#69 Add a function to check details detected license.
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/oss/view-js.jsp
Labels: enhancement

#72 Add deactivate function to OSS
  .github/workflows/release-publish.yml
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/resources/messages/message.properties
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/VerificationMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/resources/static/images/bg_toggle.png
  src/main/resources/template/email/vulnerabilityInfo.html
  src/main/webapp/WEB-INF/views/admin/license/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossAnalysisResultDetailpopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossAutoAnalysispopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/view.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Labels: enhancement, bug fix

#81 Add label:improvement to also appear as child of Feature in release draft
  .github/release-drafter-config.yml
Labels: chore

#83 Fix typo 'SourceCode' in Self-Check
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: chore

#87 Fix header column names of Vulnerability Log table
  src/main/webapp/WEB-INF/views/admin/system/vulnerabilityHistory-js.jsp
Labels: chore

#88 Expose a save button for a creator, watcher, and admin
  src/main/webapp/WEB-INF/views/admin/project/verification.jsp
Labels: improvement

#105 Drop button requires comment
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Labels: chore

#104 Rename 'Excel Download' Button to 'Export'
  src/main/webapp/WEB-INF/views/admin/license/list.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/list.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/list.jsp
Labels: chore

#71 Add license information display when clicking the Restriction icon
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
Labels: enhancement

#97 Modify pop-up phrases that occur when you press the reopen button
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Labels: chore
