Repository fosslight/fosslight, pull requests merged in 2021-06, with the labels that each got.

#3 Created Dockerfile and docker-compose.yml
  Dockerfile
  docker-compose.yml
  docker.env
Labels: enhancement

#4 Update docker files
  db/conf.d/db_config.cnf
  db/initdb.d/fosslight_create.sql
  docker-compose.yml
  docker.env
Labels: chore

#5 Move DB related files to db directory
  Dockerfile
  db/wait-for
  docker-compose.yml
  install/db/fosslight_create.sql
Labels: bug fix, chore
