Repository fosslight/fosslight, pull requests merged in 2021-12, with the labels that each got.

#305 Update Open API and deleting files function
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/repository/ApiFileMapper.java
  src/main/java/oss/fosslight/repository/ApiOssMapper.java
  src/main/java/oss/fosslight/repository/ApiProjectMapper.java
  src/main/java/oss/fosslight/service/ApiProjectService.java
  src/main/java/oss/fosslight/service/FileService.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/ApiFileMapper.xml
  src/main/resources/oss/fosslight/repository/ApiOssMapper.xml
  src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/resources/static/images/img_icon_evidence.png
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
Labels: improvement

#306 Eliminate Null Point Exception
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/domain/CoCode.java
  src/main/java/oss/fosslight/service/impl/ApiFileServiceImpl.java
  src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/validation/T2CoValidator.java
Labels: chore

#308 Change github token in code management
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
Labels: improvement

#309 Fix bugs related to partner registration
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/repository/PartnerMapper.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
Labels: chore

#278 Fix a vulnerability for resource leak
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/ImageView.java
  src/main/java/oss/fosslight/util/CompressUtil.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/java/oss/fosslight/util/FileUtil.java
Labels: chore

#295 Change the creator and modifier from ID to name in OSS list, License …
  src/main/resources/oss/fosslight/repository/LicenseMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
Labels: improvement

#313 Fix a bug for CoMailManager.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
Labels: bug fix

#318 Fix the license duplication bug in Check License
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
Labels: bug fix

#312 Change token to invisible
  src/main/java/oss/fosslight/repository/CodeMapper.java
  src/main/java/oss/fosslight/service/impl/CodeServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/resources/oss/fosslight/repository/CodeMapper.xml
  src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
Labels: chore

#322 Exception handling when accessing a deleted project
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/SelfCheckController.java
  src/main/java/oss/fosslight/repository/CodeMapper.java
  src/main/java/oss/fosslight/service/impl/CodeServiceImpl.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/oss/fosslight/repository/CodeMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
Labels: chore

#323 Change SPDX dependecy version
  build.gradle
Labels: chore

#315 Update 3rd party list UI
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/resources/static/css/commonIframe.css
  src/main/resources/static/images/img_icon_delivery_form.png
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
Labels: chore

#325 Change 3rd Party List Columns
  build.gradle
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/resources/static/css/commonIframe.css
  src/main/resources/static/images/img_icon_delivery_form.png
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
Labels: chore

#320 Fix OSS Notices to include SPDX (json) and SPDX (yaml)
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
Labels: improvement

#327 Remove the label setting for PR from the guide
  CONTRIBUTING.md
Labels: documentation

#329 Fix the bug where the notice file format is unchecked whenever the status is changed
  CONTRIBUTING.md
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
Labels: bug fix

#328 Apply autogrow to ckeditor
  src/main/resources/static/js/ckeditor/config.js
Labels: bug fix

#332 Fix heap memory issue when registering CPE Data Feed (GC Limit)
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/resources/static/js/ckeditor/config.js
Labels: bug fix

#310 Add External Service health check
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/service/AutoFillOssInfoService.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
Labels: improvement

#336 Change max height of editor
  src/main/resources/static/js/ckeditor/config.js
Labels: chore

#317 Eliminate null pointer exception in CoMailManager
  src/main/java/oss/fosslight/domain/CoMailManager.java
Labels: bug fix

#338 Add a function to change the OSS table in bulk (incomplete)
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
Labels: chore

#339 Do not print () if the OSS version is null when leaving a comment in the Check License.
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
Labels: chore

#343 Change the ckeditor config value related to file upload.
  src/main/resources/oss/fosslight/repository/DashboardMapper.xml
  src/main/resources/static/js/ckeditor/config.js
  src/main/webapp/WEB-INF/views/admin/dashboard/list-js.jsp
Labels: bug fix

#316 Eliminate null pointer exception in OSS Controller
  src/main/java/oss/fosslight/controller/OssController.java
Labels: bug fix

#344 Support Check OSS Name, Check License multilingual
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Labels: chore

#349 Fix mismatching error in Check License
  src/main/java/oss/fosslight/common/CoConstDef.java
Labels: bug fix

#355 Send comments to Creator, Watcher, and Reviewer by mail.
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/distribution-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/distribution.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification.jsp
Labels: chore

#357 Check OSS Name > Change download location to git:// from https://
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/distribution-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/distribution.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification.jsp
Labels: chore

#359 Update distribution mailing condition.
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/ComBean.java
  src/main/java/oss/fosslight/domain/CommentsHistory.java
  src/main/resources/oss/fosslight/repository/BinaryDataHistoryMapper.xml
  src/main/resources/oss/fosslight/repository/CodeMapper.xml
  src/main/resources/oss/fosslight/repository/CommentMapper.xml
  src/main/resources/oss/fosslight/repository/DashboardMapper.xml
  src/main/resources/oss/fosslight/repository/HistoryMapper.xml
  src/main/resources/oss/fosslight/repository/NoticeMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/SentMailMapper.xml
  src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
  src/main/resources/oss/fosslight/repository/T2UserMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityHistoryMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: chore

#352 Show FOSSLight version in sidebar
  build.gradle
  src/main/resources/application.properties
  src/main/resources/static/css/common.css
  src/main/resources/static/images/img_logo.png
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: chore

#356 Fix xss filter for License List with &amp;
  src/main/java/oss/fosslight/common/CustomXssFilter.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
Labels: bug fix

#362 Fix infinite loading bug when clicking Check License
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
Labels: bug fix

#365 Fix Vulnerability, Sent mail list not searchable bug
  src/main/resources/oss/fosslight/repository/BinaryDataHistoryMapper.xml
  src/main/resources/oss/fosslight/repository/CodeMapper.xml
  src/main/resources/oss/fosslight/repository/DashboardMapper.xml
  src/main/resources/oss/fosslight/repository/HistoryMapper.xml
  src/main/resources/oss/fosslight/repository/NoticeMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/SentMailMapper.xml
  src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
  src/main/resources/oss/fosslight/repository/T2UserMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityHistoryMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: bug fix

#358 License and Comment output when loading SPDX
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: chore

#364 Add Check OSS Name and Check License function in 3rd party
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/PartnerService.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
Labels: improvement

#368 Fix the bug that occurs when checking hide version in OSS notice
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/PartnerService.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: bug fix

#367 Add Check License function in Self-Check page
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: chore

#371 Fix License and Comment output when loading SPDX
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: chore

#372 Delete License output when loading SPDX
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: chore

#369 Update redistribution and vulnerability discovered mailing sql
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
  src/main/webapp/WEB-INF/views/admin/system/sentMail-js.jsp
Labels: bug fix

#353 Added function to generate OSS List through github link in Self-Check
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/controller/SelfCheckController.java
  src/main/java/oss/fosslight/controller/SystemConfigurationController.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
  src/main/webapp/WEB-INF/views/admin/system/configuration-js.jsp
  src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
Labels: enhancement

#373 Add comment output when loading SPDX
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: chore

#376 Add display in comments only when License is OR, AND
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: chore
