Repository fosslight/fosslight, pull requests merged in 2021-11, with the labels that each got.

#239 Delete the github action for merging into main
  .github/workflows/pr-close.yml
Labels: chore

#243 Fix bugs related to BOM loading and comment history
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/dashboard/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/distribution-js.jsp
Labels: bug fix

#240 Fix language select box unselected error
  src/main/resources/messages/message.properties
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/static/css/common.css
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: bug fix

#245 Fix language select box unselected error
  src/main/resources/messages/message.properties
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/static/css/common.css
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: bug fix

#237 Change CVE-ID to a link (#212)
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/resources/template/email/projectInfo.html
  src/main/resources/template/email/vulnerabilityInfo.html
Labels: improvement

#248 Changed - Recover Missing Messages
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
Labels: bug fix

#241 Fix NPE in common/CoCodeManager
  src/main/java/oss/fosslight/common/CoCodeManager.java
Labels: bug fix

#249 Fix NPE in common/CoCodeManager
  src/main/java/oss/fosslight/common/CoCodeManager.java
Labels: bug fix

#251 Fix SPDX convert error (when invalid download location)
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
Labels: bug fix

#260 Update spdx/tools-java version
  build.gradle
Labels: chore

#257 Update Check OSS Name Function
  build.gradle
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
Labels: bug fix

#262 Refactor Check License, Check OSS Name
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Labels: chore

#263 Fix the vulnerability for inapproate error message
  src/main/java/oss/fosslight/common/CoPostConstruct.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/config/AppConfig.java
  src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
  src/main/java/oss/fosslight/controller/ComplianceController.java
  src/main/java/oss/fosslight/controller/ImageViewController.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/UserController.java
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/domain/CoMail.java
  src/main/java/oss/fosslight/interceptor/AjaxInterceptor.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/util/CompressUtil.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/validation/T2CoValidator.java
Labels: chore

#268 Fix the vulnerability for inapproate error message
  src/main/java/oss/fosslight/common/CoPostConstruct.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/config/AppConfig.java
  src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
  src/main/java/oss/fosslight/controller/ComplianceController.java
  src/main/java/oss/fosslight/controller/ImageViewController.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/UserController.java
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/domain/CoMail.java
  src/main/java/oss/fosslight/interceptor/AjaxInterceptor.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/util/CompressUtil.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/validation/T2CoValidator.java
Labels: chore

#270 Fix Null pointer exception
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/common/CoCodeManager.java
  src/main/java/oss/fosslight/common/CoPostConstruct.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/config/AppConfig.java
  src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
  src/main/java/oss/fosslight/controller/ComplianceController.java
  src/main/java/oss/fosslight/controller/ImageViewController.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/UserController.java
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/domain/CoMail.java
  src/main/java/oss/fosslight/interceptor/AjaxInterceptor.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/ApiFileServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ApiOssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
  src/main/java/oss/fosslight/service/impl/HistoryServiceImpl.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/MailServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/util/CompressUtil.java
  src/main/java/oss/fosslight/util/DateUtil.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/util/FileUtil.java
  src/main/java/oss/fosslight/validation/T2CoValidator.java
Labels: chore

#266 Fix the vulnerability for public method that return private type
  src/main/java/oss/fosslight/domain/BinaryMaster.java
  src/main/java/oss/fosslight/domain/CoMail.java
  src/main/java/oss/fosslight/domain/CodeBean.java
  src/main/java/oss/fosslight/domain/ComBean.java
  src/main/java/oss/fosslight/domain/File.java
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/domain/ReportCombean.java
Labels: chore

#272 Fix the vulnerability for public method that return private type
  src/main/java/oss/fosslight/domain/BinaryMaster.java
  src/main/java/oss/fosslight/domain/CoMail.java
  src/main/java/oss/fosslight/domain/CodeBean.java
  src/main/java/oss/fosslight/domain/ComBean.java
  src/main/java/oss/fosslight/domain/File.java
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/domain/ReportCombean.java
Labels: chore

#267 Fix the vulnerability that public array is assigned to private variable
  src/main/java/oss/fosslight/domain/BinaryMaster.java
  src/main/java/oss/fosslight/domain/CodeBean.java
  src/main/java/oss/fosslight/domain/ComBean.java
  src/main/java/oss/fosslight/domain/File.java
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/domain/ReportCombean.java
Labels: chore

#273 Shorten the time required to save during OSS sync
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/BinaryMaster.java
  src/main/java/oss/fosslight/domain/CodeBean.java
  src/main/java/oss/fosslight/domain/ComBean.java
  src/main/java/oss/fosslight/domain/File.java
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/domain/ReportCombean.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
Labels: chore

#265 Add Check License in Self-Check
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: enhancement

#274 Add Check License in Self-Check
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: enhancement

#275 Create integration test codes
  src/test/java/oss/fosslight/controller/OssControllerTest.java
  src/test/java/oss/fosslight/controller/PackingRequestTest.java
  src/test/java/oss/fosslight/controller/ProjectControllerIntegrationTest.java
  src/test/java/oss/fosslight/controller/ProjectIdentificationRequestReviewIntegrationTest.java
  src/test/java/oss/fosslight/controller/ProjectIdentificationReviewConfirmIntegrationTest.java
  src/test/java/oss/fosslight/controller/SelfCheckControllerIntegrationTest.java
Labels: enhancement

#282 Update OSS Table > view comment info of oss popup
  src/main/webapp/WEB-INF/views/admin/oss/viewpopup.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: improvement

#284 Update OSS Table Function
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/service/LicenseService.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
Labels: improvement

#286 Update the project's report template
  src/main/resources/template/ProjectReport.xlsx
Labels: chore

#287 Save configuration when users search
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/SearchType.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/controller/SearchController.java
  src/main/java/oss/fosslight/repository/LicenseMapper.java
  src/main/java/oss/fosslight/repository/PartnerMapper.java
  src/main/java/oss/fosslight/repository/SearchMapper.java
  src/main/java/oss/fosslight/repository/SelfCheckMapper.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/PartnerService.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/SearchService.java
  src/main/java/oss/fosslight/service/SelfCheckService.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SearchServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/resources/oss/fosslight/repository/LicenseMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SearchMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
Labels: enhancement

#289 Fix heap memory issue when registering CPE Match Feed
  src/main/java/oss/fosslight/service/NvdDataService.java
Labels: chore

#277 Fix check oss name save error
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Labels: bug fix

#292 Add file path and copyright to Self-check
  src/main/java/oss/fosslight/api/aop/ApiControllerAspect.java
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/common/DependencyType.java
  src/main/java/oss/fosslight/common/ExternalLicenseServiceType.java
  src/main/java/oss/fosslight/service/AutoFillOssInfoService.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/template/SelfCheck-Report.xlsx
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: improvement

#255 SPDX Spreadsheet License List parsing
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: improvement

#303 Add a function to copy 3rd party to Project
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/SPDXDownloadController.java
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/VerificationService.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
Labels: enhancement

#302 Fix the vulnerability that public array is assigned to private variable
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
Labels: chore

#291 Fix a vulnerability for public methods that return private array
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
Labels: chore

#304 Fix the vulnerability that returns private variable and array
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
Labels: chore

#300 Add to show Check License conversion evidences
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/static/css/commonIframe.css
  src/main/resources/static/images/img_icon_evidence.png
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
Labels: improvement
