Repository fosslight/fosslight, pull requests merged in 2021-09, with the labels that each got.

#112 Add Docker mailserver in docker-compose
  .github/workflows/pull-request.yml
  .gitignore
  docker-compose.yml
  mail/config/dovecot-quotas.cf
  mail/config/postfix-accounts.cf
  mail/config/postfix-aliases.cf
Labels: enhancement

#110 Fix hide 'Check OSS Name' button from unrelated users
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Labels: chore

#115 3rd party/project status check function
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/3rd-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
Labels: bug fix

#82 Enhancement function : Recommend the OSS Name according to the OSS Naming Rule
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Labels: enhancement

#60 Translate some korean comments to english
  src/main/java/oss/fosslight/domain/CoMailManager.java
Labels: documentation

#116 Exclude from 'Check OSS Name' unless it is an 'Unconfirmed open source'
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Labels: bug fix

#101 Delete "Need check" in the Obligation Type from the search box in the License List
  db/initdb.d/fosslight_create.sql
Labels: chore

#114 Search website regardless of http://, https://, www.
  src/main/java/oss/fosslight/controller/OssController.java
Labels: improvement

#119 Add deploy action when develop is merged
  .github/workflows/pr-close.yml
Labels: enhancement

#120 Run docker with sudo privileges
  .github/workflows/pr-close.yml
Labels: bug fix

#123 Add alert when the number of OSS versions is 1
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Labels: improvement

#121 Add Line Separator Between Notice Intro And OSS Lists
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/resources/template/notice/notice.txt
  src/main/resources/template/notice/notice_sks.txt
Labels: improvement

#125 Add User Guide and Restriction to license popup
  src/main/webapp/WEB-INF/views/admin/selfCheck/viewpopup.jsp
Labels: improvement

#129 Add deactivate flag on getOssInfo
  src/main/resources/oss/fosslight/repository/ApiOssMapper.xml
Labels: improvement

#131 Change load all sheets starting with SRC in oss_report_src (REST_API)
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/api/controller/v1/ApiSelfCheckController.java
  src/main/java/oss/fosslight/service/ApiProjectService.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: improvement

#139 unquoted port mapping may be interpreted as a base-60 value
  docker-compose.yml
Labels: chore

#141 RestTemplate config for task 1
  src/main/java/oss/fosslight/config/RestTemplateConfig.java
  src/main/resources/application.properties
Labels: enhancement

#134 Fix the comments history shows properly in identification(project), third-party, project info tabs
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Labels: bug fix

#145 Add External Service settings to the configuration page
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/system/configuration-js.jsp
  src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
Labels: enhancement
