Repository fosslight/fosslight, pull requests merged in 2021-07, with the labels that each got.

#9 Add action for PR
  .github/workflows/pull-request.yml
  docker-compose.yml
Labels: chore

#10 Add Description of ID and Password for Demo site
  README.md
Labels: documentation

#14 Add Declared/Detected License to OSS
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/OssAnalysis.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/repository/PartnerMapper.java
  src/main/java/oss/fosslight/service/PartnerService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/oss/fosslight/repository/ApiOssMapper.xml
  src/main/resources/oss/fosslight/repository/LicenseMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/resources/template/email/ossInfo.html
  src/main/resources/template/email/ossModify.html
  src/main/webapp/WEB-INF/views/admin/oss/AJAX/ossDetailview.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossAnalysisResultDetailpopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossAutoAnalysispopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkRegpopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/view.jsp
  src/main/webapp/WEB-INF/views/admin/oss/viewpopup.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
Labels: bug fix, enhancement
