Repository fosslight/fosslight, pull requests merged in 2022-10, with the labels that each got.

#669 Show detail failure messages in OSS bulk feature.
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: enhancement

#706 Fix the broken identification ui bug
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
Labels: bug fix

#710 Fix download location check function
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/system/sentMail-js.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: bug fix

#709 Fix typo email template
  src/main/resources/template/email/changeUserInfo.html
  src/main/resources/template/email/commentWithProjectInfo.html
  src/main/resources/template/email/projectInfo.html
  src/main/resources/template/email/watcherInvated.html
Labels: chore

#707 Fix edited copyright not applied in OSS Bulk
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: bug fix

#708 Add triming logic to list attributes in OSS Bulk
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: bug fix

#714 Fix the compilation error - cannot find symbol
  src/main/java/oss/fosslight/controller/OssController.java
Labels: bug fix

#716 Change the link of OSS Name (version) in OSS registration/modification mail.
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/system/sentMail-js.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: chore

#713 Add Slack notification bot
  .github/workflows/release-publish.yml
Labels: enhancement

#719 Add latest tag to docker image
  .github/workflows/release-publish.yml
Labels: chore

#721 Highlight Oss data failed to save in red
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: improvement

#724 Fix grid data save function
  .github/workflows/release-publish.yml
  Dockerfile
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: bug fix

#726 Fix the bug where it is not merged when exporting in BOM tab.
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification.jsp
Labels: bug fix

#728 Fix a bug where the Homepage/Download Location is saved with a warning message included.
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: bug fix

#729 Display all referenceDiv like bom tab in "From column" of exported excel file
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/view.jsp
Labels: bug fix

#730 Modify oss list table in 3rd party mail
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/resources/template/email/partnerInfo.html
Labels: bug fix

#731 Fix link in registration mail OSS Name (version)
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/project/3rd-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Labels: bug fix, chore

#725 Automatically close stalled issues and pull requests
  .github/workflows/stale.yml
Labels: enhancement

#715 OSS Bulk Registration > Show warning messages
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/validation/custom/T2CoOssValidator.java
  src/main/resources/messages/validation.properties
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: improvement

#734 Remove issue auto-close
  .github/workflows/stale.yml
Labels: chore

#737 Add the file name for apex in NOTICE
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Labels: chore

#735 Separate messages of issue and pull request
  .github/workflows/stale.yml
Labels: chore

#739 Show projects regardless of permissions in the project list.
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/CoMail.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/static/images/btn_pdf.png
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/view.jsp
Labels: chore

#727 When "Change OSS Name" button is clicked, internal logic has been modified and added.
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: enhancement, chore
