Repository fosslight/fosslight, pull requests merged in 2022-04, with the labels that each got.

#465 Update OSS Type Mark > VersionDiff Service Transactional Declaration
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Labels: chore

#467 Fix the bug that an error occurs when downloading the SPDX file
  src/main/java/oss/fosslight/common/CoCodeManager.java
  src/main/java/oss/fosslight/controller/StatisticsController.java
  src/main/java/oss/fosslight/domain/CoCode.java
  src/main/java/oss/fosslight/domain/Statistics.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
Labels: bug fix

#469 Add a commit message checker
  .github/workflows/pull-request.yml
Labels: chore

#471 Add a commit message checker
  .github/workflows/pull-request.yml
Labels: chore

#473 Fix the bug of loading all licenses even though it is a dual license in Check License.
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/config/SecurityConfig.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/java/oss/fosslight/util/OssComponentUtil.java
Labels: bug fix

#476 Fix the bug where the request button disappears when packaging rejects.
  src/main/java/oss/fosslight/controller/ProjectController.java
Labels: bug fix

#480 Display the version-specific popup when click the cell of the ID column in the BOM
  src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
Labels: improvement

#478 Update newLogo in login, signup, menu bar
  src/main/resources/static/images/img_login_logo1.png
  src/main/resources/static/images/img_login_logo2.png
  src/main/resources/static/images/img_logo.png
Labels: chore

#481 Update logo in login, signup, menu bar
  src/main/resources/static/images/img_login_logo1.png
  src/main/resources/static/images/img_login_logo2.png
  src/main/resources/static/images/img_logo.png
Labels: chore

#483 Fix the error that the screen changes when user selects Reviewer from the User Setting, Project List, 3rd Party List.
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/resources/static/js/basic.js
Labels: bug fix

#484 Update the comments and messages
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/messages/message_ko_KR.properties
Labels: chore

#486 Add a Rename button to the OSS Details tab.
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
Labels: enhancement

#489 Fix a bug on clicking the Rename button
  build.gradle
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
Labels: bug fix
