Repository fosslight/fosslight, pull requests merged in 2022-08, with the labels that each got.

#621 Change the CVSS Score for sending Vulnerability alerts from 9.0 to 8.0
  src/main/java/oss/fosslight/common/AjaxSessionTimeoutFilter.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
Labels: chore

#624 When renaming to another OSS while deleting OSS, check License
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Labels: bug fix

#607 Fix return value to Obligation Type
  src/main/java/oss/fosslight/service/impl/HistoryServiceImpl.java
Labels: bug fix

#608 Add export feature to vulnerability popup
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/webapp/WEB-INF/views/admin/vulnerability/vulnpopup.jsp
Labels: enhancement

#629 When adding or copying project, remove view/edit button to addtional information.
  db/initdb.d/fosslight_create.sql
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Labels: chore

#633 Fix SPDX download error in Self-check > Notice
  src/main/java/oss/fosslight/controller/SPDXDownloadController.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
Labels: bug fix

#634 Fix the bug where SPDX download fails
  README.md
  docs/README_kor.md
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/VerificationMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: bug fix

#635 Add a Yaml button to 3rd Party, Project, Self-check
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: enhancement

#637 Fix vulnerability list > Undetected nicknames are displayed
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: bug fix

#639 Change the sheet name that is checked when uploading a file in Project Identification
  src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
Labels: chore

#640 Send an email and leave a comment if additional information is modified in Project > Basic information
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/template/sample/FOSSLight-OSS-Checklist-for-3rdParty_Eng_1.0.xlsx
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Labels: chore

#641 Fix the bug where the link changes from Check License to https://https://
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
Labels: bug fix

#642 Add 'Share URL' Button in Project, 3rd Party
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/view.jsp
Labels: enhancement

#643 Change [PRJ-ID] or [3rd-ID] text to linkable text
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/repository/PartnerMapper.java
  src/main/java/oss/fosslight/service/PartnerService.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/basic_editor.js
  src/main/webapp/WEB-INF/views/admin/license/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view.jsp
  src/main/webapp/WEB-INF/views/admin/project/AJAX/commentArea.jsp
  src/main/webapp/WEB-INF/views/admin/project/AJAX/commentPopup.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/view.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: enhancement

#636 Add project bom tab export json to the API
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/service/ApiProjectService.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/util/YamlUtil.java
Labels: enhancement

#645 Fix the bug where password cannot be set when signing up for non-LDAP
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/UserController.java
  src/main/java/oss/fosslight/repository/PartnerMapper.java
  src/main/java/oss/fosslight/service/ApiProjectService.java
  src/main/java/oss/fosslight/service/PartnerService.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/util/YamlUtil.java
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/basic_editor.js
  src/main/webapp/WEB-INF/views/admin/license/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view.jsp
  src/main/webapp/WEB-INF/views/admin/project/AJAX/commentArea.jsp
  src/main/webapp/WEB-INF/views/admin/project/AJAX/commentPopup.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/view.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: bug fix

#646 Change regular expression of project link
  src/main/resources/static/js/basic.js
Labels: chore
