Repository fosslight/fosslight, pull requests merged in 2022-03, with the labels that each got.

#420 Change self-check unclear obligation message
  build.gradle
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/ScannerController.java
  src/main/java/oss/fosslight/controller/SelfCheckController.java
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/java/oss/fosslight/util/RequestUtil.java
  src/main/java/oss/fosslight/util/StringUtil.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: chore

#421 Add vulnerability Score to 3rd party list
  build.gradle
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
Labels: chore

#425 Fix the bug where OSS is renamed when copying and saving.
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/resources/static/robots.txt
  src/main/webapp/WEB-INF/views/admin/dashboard/list.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Labels: bug fix

#426 Self-Check > Mark as obligation unclear for licenses that are not included in Declared or Detected licenses.
  src/main/java/oss/fosslight/common/CommonFunction.java
Labels: bug fix

#427 Self-check > Mark Obligation unclear for deactivate.
  src/main/java/oss/fosslight/common/CommonFunction.java
Labels: chore

#428 Fix a bug where Homepage could not be loaded for nickname when OSS Notice was issued.
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
Labels: bug fix

#429 Add a function to copy even the status when copying the project.
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/service/VerificationService.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: enhancement

#430 Show 'list more' in Vulnerability in OSS details
  src/main/java/oss/fosslight/api/advice/ExceptionAdvice.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/repository/NvdDataMapper.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/resources/application.properties
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
Labels: chore

#418 Register OSS in bulk by uploading Excel
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg.jsp
Labels: enhancement

#434 Do not load if OSS Name or Declared License is null in OSS Bulk
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: chore

#435 Add Sample template to OSS Bulk Registration
  src/main/resources/template/sample/FOSSLight-OSS-Bulk-Sample.xls
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg.jsp
Labels: chore

#439 Separate the function to check header column in OSS Bulk
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: chore

#437 Change the character that separates multiple nicknames from `\n` to `,`
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/template/sample/FOSSLight-OSS-Bulk-Sample.xls
Labels: chore

#440 Fix the bug where unregistered OSS cannot be searched by CVE-ID.
  build.gradle
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/SelfCheckController.java
  src/main/java/oss/fosslight/repository/SelfCheckMapper.java
  src/main/java/oss/fosslight/service/SelfCheckService.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/util/FileUtil.java
  src/main/java/oss/fosslight/util/YamlUtil.java
  src/main/resources/application.properties
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/resources/template/notice/selfcheck_notice.html
  src/main/resources/template/notice/selfcheck_notice.txt
  src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
  src/main/webapp/WEB-INF/views/admin/vulnerability/list-js.jsp
Labels: enhancement, bug fix

#445 Self-check > Notice tab > Don't print unconfirmed licenses
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/SessionController.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/util/YamlUtil.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
Labels: chore

#446 Fix the bug where License, OSS, Project, and 3rd Party List could not be loaded.
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/controller/SelfCheckController.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
Labels: bug fix

#444 Display pointer when mouse hovers on project name
  src/main/resources/static/css/commonIframe.css
Labels: chore

#453 adopt docker-compose Variable substitution
  docker-compose.yml
Labels: improvement

#455 Change the sheet name of the 3rd party checklist
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/template/OssCheckList.xlsx
Labels: chore

#456 Load user information from LDAP
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/domain/CoMail.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/T2UserMapper.xml
  src/main/resources/template/email/changeUserInfo.html
Labels: enhancement

#463 Fix bugs in Check License and Check OSS Name.
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
Labels: bug fix
