Repository fosslight/fosslight, pull requests merged in 2022-02, with the labels that each got.

#398 Fix the bug where the license was not displayed on the OSS details page
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
Labels: bug fix

#399 Update FOSSLight icon
  src/main/resources/static/favicon.ico
Labels: chore

#400 Add a message stating that a Notice file is required
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/static/favicon.ico
Labels: chore

#401 Change the format of OSS mail
  build.gradle
  src/main/resources/template/email/ossInfo.html
  src/main/resources/template/email/ossModify.html
Labels: chore

#402 Match OSS not deactivated in Check License
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: chore

#406 Make the Favicon background transparent
  src/main/resources/static/favicon.ico
Labels: chore

#407 Modify the written offer in notice template.
  src/main/resources/template/notice/notice.html
  src/main/resources/template/notice/notice.txt
  src/main/resources/template/notice/notice_sks.html
  src/main/resources/template/notice/notice_sks.txt
Labels: chore

#409 Fix a bug that is not searched by restriction in the License List
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/resources/oss/fosslight/repository/LicenseMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit.jsp
Labels: bug fix

#410 Fix the bug where the License List is not filtered by restriction
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/LicenseMaster.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SearchServiceImpl.java
  src/main/java/oss/fosslight/service/impl/StatisticsServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/LicenseMapper.xml
  src/main/webapp/WEB-INF/views/admin/configuration/AJAX/searchConditionArea.jsp
  src/main/webapp/WEB-INF/views/admin/license/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/list.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: chore

#411 Update version to 1.2.30
  build.gradle
Labels: documentation

#414 Add a comment to the Project mail
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/template/email/projectInfo.html
Labels: chore

#415 Check Oss Name > npm > registered OSS Name
  src/main/java/oss/fosslight/api/controller/v1/ApiBatController.java
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: chore

#416 Fix the bug where the notification doesn't pop up.
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/SelfCheckController.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/repository/FileMapper.java
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/resources/oss/fosslight/repository/FileMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/system/notice-js.jsp
Labels: bug fix

#417 Add Division to Project, 3rd Party.
  build.gradle
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/ApiPartnerMapper.xml
  src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
  src/main/resources/oss/fosslight/repository/ApiSelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/DashboardMapper.xml
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: enhancement
