Repository fosslight/fosslight, pull requests merged in 2022-05, with the labels that each got.

#492 When copying OSS and Project, try setting the name and version.
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
Labels: chore

#493 Fix bug where suffix is added twice in version
  src/main/java/oss/fosslight/controller/ProjectController.java
Labels: bug fix

#494 Fix bug where suffix is added twice in version
  src/main/java/oss/fosslight/controller/ProjectController.java
Labels: bug fix

#496 After deleting the uploaded file in Self-check, change the error that occurs when saving.
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: bug fix

#498 Fix the page not showing in OSS Bulk
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg.jsp
Labels: bug fix

#500 Fix the bug if the download location is null
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Labels: bug fix

#501 Fix the bug if the download location is null
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Labels: bug fix

#503 Change Status Message for Row Registration Failed in OSS Bulk
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: chore

#506 Check OSS Name, License > Change the way you find links
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: chore

#507 Add model updates to the API
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: enhancement

#511 Update the release note
  RELEASE_NOTES.md
Labels: documentation

#512 Add release note link to README
  docs/README_kor.md
Labels: documentation

#513 When copying a project, add a pop-up to choose which level to copy to.
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
Labels: enhancement

#514 API > Update models regardless of status
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
Labels: chore

#515 When issuing a Notice in Self-check, load and include the OSS link instead of the Homepage by loading the Download location
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
Labels: chore

#516 Fix the bug where the distribution site is changed when the model is updated with the api
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
Labels: bug fix

#517 Fix the bug where the model cannot be found
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
Labels: bug fix

#518 Add validation error message
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
Labels: chore

#519 Update version to 1.3.8
  build.gradle
Labels: documentation

#520 Change the UI for self-check upload
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: chore

#524 If a Short Identifier exists in the License, display it as Short ID.
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/java/oss/fosslight/validation/custom/T2CoOssValidator.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/ossAnalysisResultDetailpopup.jsp
Labels: chore

#525 Fix OSS bulk registration bugs
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Labels: bug fix

#528 Fix the bug that the file is deleted when copying
  build.gradle
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/repository/FileMapper.java
  src/main/java/oss/fosslight/service/FileService.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/FileMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Labels: bug fix

#530 API > Add parameters to model_update
  src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: chore
