Repository fosslight/fosslight, pull requests merged in 2022-06, with the labels that each got.

#531 Upgrade Java version to 11
  .github/workflows/release-publish.yml
  Dockerfile
  build.gradle
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/util/SPDXUtil2.java
Labels: chore

#532 Update link of version
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: chore

#533 Add check license button to Self-check
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: chore

#538 Update version to 1.4.0
  RELEASE_NOTES.md
  build.gradle
  docs/RELEASE_NOTES_kor.md
Labels: documentation

#539 Update the release note
  RELEASE_NOTES.md
  docs/RELEASE_NOTES_kor.md
Labels: documentation

#541 Change 'oss List' to 'OSS List'.
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: chore

#540 Change the column name to CVSS Score to Vulnerability in Self Check Tab
  src/main/webapp/WEB-INF/views/admin/selfCheck/list-js.jsp
Labels: chore

#544 Update Spring boot version 2.1.7 to 2.6.8
  build.gradle
  src/main/java/oss/fosslight/common/CorsFilter.java
  src/main/resources/application.properties
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
Labels: bug fix, chore

#547 Shorten the long loading time when viewing the OSS List.
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
Labels: chore

#548 Update the release notes
  RELEASE_NOTES.md
  build.gradle
  docs/RELEASE_NOTES_kor.md
Labels: documentation

#550 Update UI (Creator/Division/Reviewer) - change the width
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/resources/template/email/ossInfo.html
  src/main/resources/template/email/ossModify.html
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
Labels: chore

#551 Update download location and homepage > same link check condition
  RELEASE_NOTES.md
  build.gradle
  docs/RELEASE_NOTES_kor.md
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
Labels: chore

#554 Copy whether notice has been modified or not
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
Labels: bug fix

#555 open oss details window in oss version information
  src/main/webapp/WEB-INF/views/admin/oss/AJAX/ossDetailview.jsp
Labels: enhancement
