Repository fosslight/fosslight, pull requests merged in 2022-12, with the labels that each got.

#767 Fix license name saved redundantly
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Labels: bug fix

#766 chore: Configure Dependabot for GitHub Actions
  .github/dependabot.yml
Labels: chore

#772 LDAP > Fix a bug that caused an error when the password was incorrect.
  src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
Labels: bug fix

#771 OSS Bulk Registration > Fix type of some fields to textarea
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: improvement

#775 Vulnerability > Change OSS Name matching method (improved accuracy)
  build.gradle
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/repository/NvdDataMapper.java
  src/main/java/oss/fosslight/repository/VulnerabilityMapper.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/resources/template/email/vulnerabilityInfo.html
  src/main/webapp/WEB-INF/views/admin/vulnerability/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/vulnerability/list.jsp
Labels: chore

#776 Fix bug where vulnerability cannot be found if there is a space in the OSS Name.
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/repository/SelfCheckMapper.java
  src/main/java/oss/fosslight/service/impl/ApiVulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
  src/main/resources/oss/fosslight/repository/ApiVulnerabilityMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: bug fix

#778 Fix bug with create project for OSS Notice
  LICENSES/LicenseRef-3rd_party_licenses.txt
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Labels: bug fix

#779 Fix vulnerability search condition and when save vendor data
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/config/AppConfig.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/repository/SelfCheckMapper.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/webapp/WEB-INF/constants.jsp
  src/main/webapp/WEB-INF/views/admin/configuration/edit.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossAnalysisResultDetailpopup.jsp
  src/main/webapp/WEB-INF/views/admin/system/configuration-js.jsp
  src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
  src/main/webapp/WEB-INF/views/admin/system/user-js.jsp
Labels: bug fix

#780 Update 3rd party licenses
  LICENSES/LicenseRef-3rd_party_licenses.txt
Labels: documentation

#785 Fix a bug where a space is added at the beginning when there are more than two detected licenses when loading OSS
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/template/email/ossModify.html
  src/main/webapp/WEB-INF/views/admin/oss/ossAnalysisResultDetailpopup.jsp
Labels: bug fix
