Repository fosslight/fosslight, pull requests merged in 2022-11, with the labels that each got.

#740 Check OSS Name > Change the redirect url automatically.
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: enhancement

#741 Project List > Fix bugs related to View my project only
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: bug fix

#742 (Experimental) Add file extraction tag in Notice of Android
  src/main/java/oss/fosslight/common/CommonFunction.java
Labels: chore

#744 Project List > Fix a bug that caused a permission error when clicking on an empty space in Identification.
  src/main/resources/static/js/basic.js
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Labels: bug fix

#745 Fix issuance of notice for permissive license
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/statistics/statisticspopup.jsp
Labels: bug fix

#746 Add code for Vulnerability Notification Score to code management (Code No. 750)
  db/initdb.d/fosslight_create.sql
Labels: chore

#747 Add check email when login new user
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/config/AppConstBean.java
  src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
  src/main/java/oss/fosslight/config/CustomWebAuthenticationDetails.java
  src/main/java/oss/fosslight/config/CustomWebAuthenticationDetailsSource.java
  src/main/java/oss/fosslight/config/SecurityConfig.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/service/impl/T2UserServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/webapp/WEB-INF/views/admin/statistics/statisticspopup.jsp
  src/main/webapp/WEB-INF/views/admin/statistics/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/statistics/view.jsp
Labels: bug fix

#749 Add Android format(android.googlesource.com/platform/) to change oss name.
  build.gradle
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Labels: enhancement

#753 Possible to select other version of oss even if the information is same in oss sync
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/oss/syncpopup.jsp
Labels: chore

#754 When export the specific oss name of vulnerablity, append oss name to exported file name
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
Labels: chore

#755 Display the latest oss information which has nickname or oss name of auto analysis result
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
Labels: bug fix, chore

#756 When sync oss, it is also possible to update only comment.
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/webapp/WEB-INF/views/admin/oss/syncpopup.jsp
Labels: chore

#757 In oss detail popoup, it is available to copy oss
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Labels: bug fix

#758 Exclude deactivated OSS from analysis results
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
Labels: chore

#751 Upload review report html template
  src/main/resources/template/report/reviewReport.html
Labels: enhancement

#761 Display "Required oss name" warning message
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/messages/validation.properties
Labels: enhancement

#763 Display "Required oss name" warning message when oss name is "-" and license has source obligation.
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/messages/validation.properties
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/webapp/WEB-INF/views/admin/project/3rd-js.jsp
Labels: enhancement, bug fix, chore

#764 Fix bug where license is not merged in BOM if it is blank
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Labels: bug fix

#765 LDAP > Modify the updated date to be displayed in user information when sending mail.
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/T2Users.java
  src/main/resources/oss/fosslight/repository/T2UserMapper.xml
Labels: chore
