Repository fosslight/fosslight, pull requests merged in 2022-09, with the labels that each got.

#647 When sending 3rd party confirmed mail, attach the list of disclose oss.
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/Vulnerability.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/resources/static/js/basic.js
  src/main/resources/template/email/partnerInfo.html
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view.jsp
  src/main/webapp/WEB-INF/views/admin/project/AJAX/commentArea.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/view-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/view.jsp
Labels: enhancement, bug fix, chore

#651 Fix bug where watcher row is duplicated in project basic information
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
Labels: bug fix

#653 Add logic to validate for download location from input data
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
Labels: chore

#654 Remove duplicated oss list in 3rd party mail
  src/main/java/oss/fosslight/domain/CoMailManager.java
Labels: chore

#655 Increase the height of oss version list table in oss version list popup
  src/main/webapp/WEB-INF/views/admin/oss/viewpopup.jsp
Labels: chore

#657 Check user permission when changing divisions.
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Labels: chore

#658 Add the NPM link pattern
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
Labels: chore

#659 Remove buttons at the bottom of the table.
  src/main/webapp/WEB-INF/views/admin/compliance/3rdList.jsp
  src/main/webapp/WEB-INF/views/admin/compliance/modelStatus.jsp
  src/main/webapp/WEB-INF/views/admin/license/list.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
  src/main/webapp/WEB-INF/views/admin/project/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/list.jsp
  src/main/webapp/WEB-INF/views/admin/vulnerability/list.jsp
Labels: chore

#660 Change downloaded file name when clicking export button
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/java/oss/fosslight/util/YamlUtil.java
Labels: chore

#661 Fix oss sync function for regist comment
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/syncpopup.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
Labels: chore

#662 Change buttons to be top of the table in Binary DB, System > User management
  src/main/webapp/WEB-INF/views/admin/system/binaryDataHistory.jsp
  src/main/webapp/WEB-INF/views/admin/system/user.jsp
Labels: chore

#663 Send email with oss list and disclose oss list
  db/initdb.d/fosslight_create.sql
  src/main/resources/template/email/partnerInfo.html
  src/main/resources/template/email/projectInfo.html
Labels: chore

#668 Add "search icon" in filter cell of table
  src/main/resources/static/css/jqgrid4.7/ui.jqgrid.css
Labels: enhancement

#673 Change search icon file
  src/main/resources/static/css/jqgrid4.7/ui.jqgrid.css
  src/main/resources/static/images/search.png
Labels: chore

#674 Change the label text to result.txt and binary.txt to fosslight_binary.txt.
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/messages/validation.properties
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Labels: chore

#656 Add editable and selectable to ossBulkRegRows
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: enhancement

#676 Add oss list in identification confirm mail
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/static/css/jqgrid4.7/ui.jqgrid.css
  src/main/resources/template/email/projectInfo.html
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: chore

#664 Self-check > Add SPDX as well as FOSSLight Report to the export button download
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: enhancement

#679 Display division information even if Use YN flag of division is N
  src/main/webapp/WEB-INF/views/admin/configuration/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/view.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/view.jsp
Labels: bug fix

#678 Fix the typo in OSS Detail tab. (Atrribution -> Attribution)
  src/main/resources/messages/message_ko.properties
Labels: chore

#681 Fix bug where CVE-ID is displayed as duplicate in OSS details tab
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Labels: bug fix

#684 When click "+" button, insert new row at the top of the table
  src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Labels: chore

#686 Fix the bug where the license flag is not saved when saving OSS
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Labels: bug fix

#652 Auto upload identification invalid data to oss bulk registration
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Labels: enhancement

#689 Fix a bug where only 1 Vulnerability list is shown when there is no version in OSS detail page
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: bug fix

#691 Project > 3rd Party tab > Leave a comment on the history of changing nickname.
  src/main/java/oss/fosslight/controller/ProjectController.java
Labels: chore

#692 When division information is changed, do not save automatically.
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
Labels: bug fix

#693 Fix the bug where the license written as nickname does not change to license name when save is clicked
  src/main/java/oss/fosslight/domain/OssComponents.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Labels: bug fix

#650 Support SPDX download in bom tab
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Labels: improvement

#696 Fix the bug that the row in which only Homepage or Copyright is entered is not loaded when uploading a report.
  src/main/java/oss/fosslight/common/CommonFunction.java
Labels: bug fix

#697 Fix a bug that occurs when saving to 3rd party tab in project
  src/main/java/oss/fosslight/domain/OssComponents.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: bug fix

#698 In 3rd party confirm mail, add "need to disclose" column
  db/initdb.d/fosslight_create.sql
  src/main/resources/template/email/partnerInfo.html
Labels: enhancement

#699 Add license text files
  LICENSES/AGPL-3.0.txt
  LICENSES/LicenseRef-3rd_party_licenses.txt
Labels: chore

#675 Deploy image to Docker Hub
  .github/workflows/release-publish.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement

#702 Remove the limit on the number of rows for the bulk edit button
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: bug fix

#700 Add license text files to docker image
  Dockerfile
Labels: chore

#704 In comment mail, activate project/3rd party link
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
Labels: bug fix
