Repository fosslight/fosslight, pull requests merged in 2022-07, with the labels that each got.

#557 Packaging > Notice tab > edit html > Show message if checked.
  RELEASE_NOTES.md
  build.gradle
  db/initdb.d/fosslight_create.sql
  docs/RELEASE_NOTES_kor.md
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/MailManagerMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/project/verification.jsp
Labels: chore

#559 Fix bug where CVE-ID is returned as duplicate in API > Vulnerability.
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/service/impl/ApiVulnerabilityServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Labels: bug fix

#560 Fix the bug where uploaded files are not visible
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Labels: bug fix

#561 Hide user email as per option
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/webapp/WEB-INF/views/admin/system/user-js.jsp
Labels: chore

#562 Fix the bug where sorting by column is not possible in the 3rd party list
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Labels: bug fix

#563 Update version to 1.4.4
  build.gradle
Labels: documentation

#565 Show the project list in Opened Jobs of Dashboard when user is not admin
  src/main/resources/oss/fosslight/repository/DashboardMapper.xml
Labels: bug fix

#566 Change yaml file format when oss list is exported as yaml
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/util/YamlUtil.java
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
Labels: improvement

#571 Update Dockerfile for Mac M1
  Dockerfile
Labels: chore

#573 (Experimental) Update BAT > show GUI report icon
  RELEASE_NOTES.md
  build.gradle
  docs/RELEASE_NOTES_kor.md
  src/main/java/oss/fosslight/controller/DownloadProcController.java
  src/main/java/oss/fosslight/controller/ImageViewController.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: chore

#568 Modify reloaded identification tab after 'change license' or 'change nickname' to you're working on.
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Labels: improvement

#586 Add the function to change division
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/service/PartnerService.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/messages/message_en_US.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/resources/static/js/basic.js
  src/main/webapp/WEB-INF/views/admin/oss/ossAutoAnalysispopup.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/list.jsp
Labels: enhancement

#587 Add a flag to use the license's internal url
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/webapp/WEB-INF/views/admin/license/edit.jsp
Labels: chore

#594 Fix the error that occurs when clicking Check OSS Name in 3rd party
  RELEASE_NOTES.md
  build.gradle
  docs/RELEASE_NOTES_kor.md
  src/main/java/oss/fosslight/util/ExcelUtil.java
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Labels: bug fix

#593 Hide user email as per option
  src/main/webapp/WEB-INF/views/admin/system/user-js.jsp
Labels: chore

#592 Change the multilingual setting to ignore the country
  src/main/java/oss/fosslight/config/WebConfig.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
Labels: bug fix

#572 Show "Double click" when mouse hovers on project name
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Labels: chore

#588 XSS prevention with jstl
  src/main/webapp/WEB-INF/views/admin/selfCheck/AJAX/view.jsp
Labels: chore

#583 Fix comment in Self-check to remove newline
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Labels: chore

#591 Make it search even if space is included at the beginning and end of the word in the OSS List
  src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
Labels: chore

#598 Fix bugs that do not run with docker-compose on Windows
  Dockerfile
  db/wait-for
Labels: bug fix

#603 Fix the bug where search terms are entered during change division
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/webapp/WEB-INF/views/admin/compliance/modelStatus-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/list.jsp
Labels: bug fix

#609 Remove version diff notification popup when deleting OSS
  src/main/java/oss/fosslight/validation/custom/T2CoOssValidator.java
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Labels: bug fix

#600 Add guide comment in Configuration
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
Labels: chore

#580 Move to a cell what I double-click
  src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Labels: chore

#604 Increase the length of the name field
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
Labels: chore

#602 Add priority to the status tooltip of the Project List
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Labels: chore

#610 Caching Dependencies to speed up workflows
  .github/workflows/pull-request.yml
  .github/workflows/release-publish.yml
Labels: chore

#613 Increase the length of the project's name field
  src/main/webapp/WEB-INF/views/admin/project/edit.jsp
Labels: chore

#616 Show the user's name, when Mouse hover
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: chore
