Repository fosslight/fosslight, pull requests merged in 2023-03, with the labels that each got.

#823 Fix function from ldap simple binding to ldap secure
  build.gradle
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/repository/VulnerabilityMapper.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/T2UserServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/resources/template/email/partnerModify.html
  src/main/resources/template/email/projectInfo.html
  src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
Labels: bug fix

#826 Fix bugs without vulnerabilities when OSS version blank
  src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/T2UserServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
Labels: bug fix

#827 Fix bug where Vulnerability is incorrectly displayed for OSS Name :-.
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
Labels: bug fix

#828 Add the file name and code values for the LDAP settings
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CommonFunction.java
Labels: chore

#829 Fix bug where not all matched CVEs were retrieved.
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: bug fix

#830 Fix release date data check function when model list upload
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelUtil.java
Labels: bug fix

#831 Add a file to use mybatis migrations
  LICENSES/LicenseRef-3rd_party_licenses.txt
  migration/migration/README
  migration/migration/drivers/mariadb-java-client-2.7.2.jar
  migration/migration/environments/development.properties
  migration/migration/scripts/20230322085317_create_changelog.sql
  migration/migration/scripts/20230322091138_update_v1.4.9.sql
  migration/migration/scripts/20230322092534_update_v1.5.0.sql
  migration/migration/scripts/bootstrap.sql
  migration/mybatis-migrations-3.3.11/LICENSE
  migration/mybatis-migrations-3.3.11/NOTICE
  migration/mybatis-migrations-3.3.11/README.md
  migration/mybatis-migrations-3.3.11/bin/migrate
  migration/mybatis-migrations-3.3.11/bin/migrate.cmd
  migration/mybatis-migrations-3.3.11/lib/mybatis-3.5.10.jar
  migration/mybatis-migrations-3.3.11/lib/mybatis-migrations-3.3.11.jar
  sbom-info.yaml
Labels: chore

#813 Add reset password feature
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/config/SecurityConfig.java
  src/main/java/oss/fosslight/controller/UserController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/resources/static/css/common.css
  src/main/resources/template/email/resetUserPassword.html
  src/main/webapp/WEB-INF/views/session/login.jsp
Labels: enhancement
