Repository fosslight/fosslight, pull requests merged in 2023-09, with the labels that each got.

#931 OSS > add > new icon for newly added nicknames
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit.jsp
Labels: enhancement

#974 Add stackoverflow pattern for check oss name
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
Labels: enhancement

#933 Modify to do not have to press the search button
  src/main/webapp/WEB-INF/views/admin/project/bomCompare-js.jsp
Labels: improvement

#971 Fix the RUN script format of Dockerfile
  Dockerfile
Labels: chore

#984 Combine comment into one when packaging confirm
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/service/VerificationService.java
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
Labels: improvement

#937 Fix to show multiple notifications
  src/main/java/oss/fosslight/config/SecurityConfig.java
  src/main/resources/oss/fosslight/repository/NoticeMapper.xml
  src/main/resources/static/css/common.css
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/session/login.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/template.jsp
Labels: improvement

#983 Add vulnerability search to OSS List
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/webapp/WEB-INF/views/admin/configuration/AJAX/searchConditionArea.jsp
  src/main/webapp/WEB-INF/views/admin/oss/list.jsp
Labels: enhancement
