Repository fosslight/fosslight, pull requests merged in 2023-01, with the labels that each got.

#786 Print partner name in excel BOM
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
Labels: chore

#787 Print partner name in excel BOM
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
Labels: chore

#789 When project identification is confirmed, the information of bom tab is updated based on DB.
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: enhancement

#790 Possible to check the recommended OSS Name even if the download location is not valid
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Labels: enhancement

#791 Check License > display "Changed" text when license is changed successfully
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/messages/validation.properties
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
  src/main/webapp/WEB-INF/views/admin/vulnerability/vulnpopup.jsp
Labels: bug fix

#795 Fix bug with previously generated OSS notices
  src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
Labels: bug fix

#797 Binary Auto Identification
  build.gradle
  db/initdb.d/fosslight_create.sql
  libs/tlsh-4.6.0.jar
  src/main/java/oss/fosslight/controller/BinaryDataController.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/BinaryData.java
  src/main/java/oss/fosslight/repository/BinaryDataMapper.java
  src/main/java/oss/fosslight/service/AutoIdService.java
  src/main/java/oss/fosslight/service/BinaryDataService.java
  src/main/java/oss/fosslight/util/TlshUtil.java
  src/main/resources/application.properties
  src/main/resources/oss/fosslight/repository/BinaryDataMapper.xml
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/admin/binary/binarypopup.jsp
  src/main/webapp/WEB-INF/views/admin/binary/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/binary/list.jsp
  src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
  src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Labels: enhancement

#798 Bug fix - Fail to remove the compressed notice file in BIN(Android)
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: bug fix

#800 Remove all files and folder related to compressed notice file.
  src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
Labels: chore

#784 License Bulk Registration
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/service/LicenseService.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoLicenseValidator.java
  src/main/webapp/WEB-INF/views/admin/license/licenseBulkReg-js.jsp
Labels: enhancement

#803 Fix the bug - fail to load autoanalysis result
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: bug fix

#804 Uploading/removing files works independently of clicking the "save" button in BIN(Android)
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: enhancement
