Repository fosslight/fosslight, pull requests merged in 2023-08, with the labels that each got.

#859 Change string concatenation method
  src/main/java/oss/fosslight/util/StringUtil.java
Labels: chore

#760 Add Attach Pdf to Email
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/util/PdfUtil.java
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
Labels: enhancement, keep

#921 Remove Unused Parameter 'binaryName' in Function
  src/main/java/oss/fosslight/service/AutoIdService.java
Labels: chore

#905 Fix a typo at Url
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/ProjectController.java
Labels: chore

#898 Fix a typo of CoMail's getSndSeq comment
  src/main/java/oss/fosslight/domain/CoMail.java
Labels: chore

#917 Block unsupported file extensions in the packaging tab
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
Labels: enhancement

#930 Remove unused Slack notification step
  .github/workflows/release-publish.yml
Labels: chore

#934 Added watcher search box in Project List, 3rd Party List
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/configuration/AJAX/searchConditionArea.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/list.jsp
Labels: enhancement
