Repository fosslight/fosslight, pull requests merged in 2023-04, with the labels that each got.

#834 Change method from NVD Data feeds to REST API
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/config/SecurityConfig.java
  src/main/java/oss/fosslight/controller/UserController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/repository/NvdDataMapper.java
  src/main/java/oss/fosslight/scheduler/SchedulerWorkerTask.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
  src/main/resources/oss/fosslight/repository/PartnerMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/static/css/common.css
  src/main/resources/template/email/projectInfo.html
  src/main/resources/template/email/resetUserPassword.html
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
  src/main/webapp/WEB-INF/views/session/login.jsp
Labels: bug fix

#835 Fix project list cvss score maximum value select query
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/repository/NvdDataMapper.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/oss/syncpopup.jsp
  src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
  src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
Labels: bug fix

#837 Fix a typo in the notice template
  src/main/resources/template/notice/notice.txt
Labels: chore

#838 Improve the speed of loading oss table.
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/template/notice/notice.txt
Labels: bug fix, chore

#839 Bug fix where uploading csv file via self-check oss-report-selfcheck API.
  src/main/java/oss/fosslight/api/controller/v1/ApiSelfCheckController.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Labels: bug fix

#840 Check oss name - the oss matched with name and version is existed and download location has "Not the same as property" warning message
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Labels: bug fix
