Repository fosslight/fosslight, pull requests merged in 2023-02, with the labels that each got.

#805 After the Identification stage is confirmed, copyright text column is updated based on db
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Labels: bug fix

#806 Fix the bug that the Vulnerability popup is not searched if there is a space in the OSS Name
  src/main/java/oss/fosslight/controller/VulnerabilityController.java
Labels: bug fix

#807 Fix the vulnerability issue in NOTICE.html
  src/main/resources/template/notice/notice.html
  src/main/resources/template/notice/notice_sks.html
  src/main/resources/template/notice/selfcheck_notice.html
Labels: chore

#809 Fix bug where OSS Name/Nickname does not match NVD Data when there is a space
  src/main/java/oss/fosslight/api/advice/ExceptionAdvice.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/CodeServiceImpl.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/resources/ehcache.xml
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: bug fix

#811 Fix the bug where sending vulnerability mail when " " or "-" is included in OSS Name
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
Labels: bug fix

#812 Add checking validation of binary db data
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/VulnerabilityController.java
  src/main/java/oss/fosslight/domain/BinaryData.java
  src/main/java/oss/fosslight/repository/NvdDataMapper.java
  src/main/java/oss/fosslight/repository/VulnerabilityMapper.java
  src/main/java/oss/fosslight/service/BinaryDataService.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: enhancement, bug fix

#814 fix vulnerability check function in identification tab
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/resources/static/css/jquery-ui.css
  src/main/resources/static/css/jquery.qtip.css
  src/main/resources/static/css/jquery.qtip.min.css
  src/main/resources/static/js/alertifyjs/alertify.js
  src/main/resources/static/js/alertifyjs/alertify.min.js
  src/main/resources/static/js/alertifyjs/css/alertify.css
  src/main/resources/static/js/alertifyjs/css/alertify.min.css
  src/main/resources/static/js/alertifyjs/css/alertify.rtl.css
  src/main/resources/static/js/alertifyjs/css/alertify.rtl.min.css
  src/main/resources/static/js/alertifyjs/css/themes/bootstrap.css
  src/main/resources/static/js/alertifyjs/css/themes/bootstrap.min.css
  src/main/resources/static/js/alertifyjs/css/themes/bootstrap.rtl.css
  src/main/resources/static/js/alertifyjs/css/themes/bootstrap.rtl.min.css
  src/main/resources/static/js/alertifyjs/css/themes/default.css
  src/main/resources/static/js/alertifyjs/css/themes/default.min.css
  src/main/resources/static/js/alertifyjs/css/themes/default.rtl.css
  src/main/resources/static/js/alertifyjs/css/themes/default.rtl.min.css
  src/main/resources/static/js/alertifyjs/css/themes/semantic.css
  src/main/resources/static/js/alertifyjs/css/themes/semantic.min.css
  src/main/resources/static/js/alertifyjs/css/themes/semantic.rtl.css
  src/main/resources/static/js/alertifyjs/css/themes/semantic.rtl.min.css
  src/main/resources/static/js/jquery-1.11.0.min.js
  src/main/resources/static/js/jquery-migrate-1.2.1.min.js
  src/main/resources/static/js/jquery-ui.min.js
  src/main/resources/static/js/jquery.qtip.js
  src/main/resources/static/js/jquery.qtip.min.js
  src/main/webapp/WEB-INF/views/main/index.jsp
  src/main/webapp/WEB-INF/views/session/login.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/scripts.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/scripts_ifr4.7.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/scripts_popup4.7.jsp
Labels: bug fix

#815 When saving basic information, if the required fields are omitted, automatically focus on them
  db/initdb.d/fosslight_create.sql
  src/main/resources/static/js/basic.js
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Labels: chore

#818 Fix the ability to load vulnerability data in the identification tab
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CoConstDef.java
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/controller/LicenseController.java
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/domain/CoMailManager.java
  src/main/java/oss/fosslight/domain/ComBean.java
  src/main/java/oss/fosslight/domain/OssMaster.java
  src/main/java/oss/fosslight/domain/ProjectIdentification.java
  src/main/java/oss/fosslight/repository/OssMapper.java
  src/main/java/oss/fosslight/repository/ProjectMapper.java
  src/main/java/oss/fosslight/service/OssService.java
  src/main/java/oss/fosslight/service/ProjectService.java
  src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
  src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/oss/fosslight/repository/LicenseMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
  src/main/resources/static/js/basic.js
  src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg.jsp
  src/main/webapp/WEB-INF/views/main/index.jsp
  src/main/webapp/WEB-INF/views/session/login.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/scripts.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/scripts_ifr4.7.jsp
  src/main/webapp/WEB-INF/views/template/layout/admin/scripts_popup4.7.jsp
Labels: enhancement, bug fix, chore

#819 Fix Vulnerability issue
  src/main/java/oss/fosslight/controller/OssController.java
  src/main/java/oss/fosslight/domain/Vulnerability.java
  src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: bug fix

#820 In 3rd party, "OSS Bulk Registration" is possible.
  src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
Labels: enhancement

#822 Fix vulnerability data matching condition
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/repository/NvdDataMapper.java
  src/main/java/oss/fosslight/service/NvdDataService.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
  src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
  src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
  src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Labels: bug fix
