Repository fosslight/fosslight, pull requests merged in 2023-11, with the labels that each got.

#1011 In BOM tab, append all copyright when oss name and oss version is same.
  db/initdb.d/fosslight_create.sql
  src/main/java/oss/fosslight/common/CommonFunction.java
  src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
  src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
  src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
  src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/oss/fosslight/repository/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/admin/configuration/AJAX/searchConditionArea.jsp
  src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/dep-js.jsp
Labels: enhancement, bug fix

#1013 Added "Change" Button in Project List, 3rd Party List
  src/main/java/oss/fosslight/common/Url.java
  src/main/java/oss/fosslight/controller/PartnerController.java
  src/main/java/oss/fosslight/controller/ProjectController.java
  src/main/java/oss/fosslight/controller/VerificationController.java
  src/main/java/oss/fosslight/domain/PartnerMaster.java
  src/main/java/oss/fosslight/domain/Project.java
  src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
  src/main/resources/messages/message_en.properties
  src/main/resources/messages/message_ko.properties
  src/main/resources/oss/fosslight/repository/OssMapper.xml
  src/main/resources/static/css/commonIframe.css
  src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/oss/edit.jsp
  src/main/webapp/WEB-INF/views/admin/oss/ossAnalysisResultDetailpopup.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/partner/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/distribution-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/identification.jsp
  src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/list.jsp
  src/main/webapp/WEB-INF/views/admin/project/secCommon-js.jsp
  src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
  src/main/webapp/WEB-INF/views/admin/selfCheck/verification-js.jsp
Labels: enhancement

#996 Build docker image with Jib
  .github/workflows/release-publish.yml
  docker-compose.yml
Labels: chore, stale

#1012 Replace docker base image from adopt to temulin
  Dockerfile
Labels: chore

#1014 Update docker-related files
  .github/workflows/release-publish.yml
  Dockerfile
  build.gradle
Labels: chore
